{% set name = "cocopye" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cocopye-{{ version }}.tar.gz
  sha256: 2cd579498f3159120c4d5ad3a82261da6fd9c86d441093e0f178fa4ef3d444a2

build:
  entry_points:
    - cocopye = cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy >=1.23
    - numba >=0.56.4
    - biopython ==1.81
    - scikit-learn ==1.3.1
    - pandas
    - packaging
    - appdirs >=1.4.4,<1.5.dev0
    - tomlkit >=0.11.6,<0.12.dev0
    - requests >=2.31.0,<2.32.dev0
    - tqdm >=4.65.0,<4.66.dev0
    - numba-progress ==1.0.0
    - uproc ==1.2.0

test:
  imports:
    - cocopye
  commands:
    - pip check
    - cocopye --help
  requires:
    - pip

about:
  home: https://github.com/gobics/cocopye
  summary: Feature-based prediction of genome quality indices
  dev_url: https://github.com/gobics/cocopye
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - njbirth
